// hpo-modifier.component.stories.ts
import type { Meta, StoryObj } from '@storybook/angular';
import { moduleMetadata } from '@storybook/angular';
import { HpoModifierComponent } from './hpo-modifier.component';
import { HpoTermMinimal } from '../models/hpo-annotation-models';

const SAMPLE_MODIFIERS: HpoTermMinimal[] = [
  { termId: 'HP:0012825', label: 'Mild' },
  { termId: 'HP:0012826', label: 'Moderate' },
  { termId: 'HP:0012828', label: 'Severe' },
  { termId: 'HP:0031375', label: 'Insidious onset' },
  { termId: 'HP:0003679', label: 'Static' },
  { termId: 'HP:0003676', label: 'Progressive' },
];

const meta: Meta<HpoModifierComponent> = {
  title: 'Components/HpoModifier',
  component: HpoModifierComponent,
  decorators: [
    moduleMetadata({
      imports: [HpoModifierComponent],
    }),
  ],
  // required input MUST be supplied here, or Storybook renders before Angular
  // sets it and you get NG0950 — same class of bug as the earlier input.required() fix
  args: {
    availableModifiers: SAMPLE_MODIFIERS,
    selectedModifiers: [],
  },
  argTypes: {
    modifierToggled: { action: 'modifierToggled' },
    menuClosed: { action: 'menuClosed' },
    selectedModifiersChange: { action: 'selectedModifiersChange' }, // auto-generated by model()
  },
};

export default meta;
type Story = StoryObj<HpoModifierComponent>;

export const Default: Story = {
  args: {
    availableModifiers: SAMPLE_MODIFIERS,
    selectedModifiers: [],
  },
};

export const WithPreselectedModifiers: Story = {
  args: {
    availableModifiers: SAMPLE_MODIFIERS,
    selectedModifiers: [SAMPLE_MODIFIERS[1], SAMPLE_MODIFIERS[4]], // Moderate + Static
  },
};

export const AllSelected: Story = {
  args: {
    availableModifiers: SAMPLE_MODIFIERS,
    selectedModifiers: SAMPLE_MODIFIERS,
  },
};

export const NoModifiersAvailable: Story = {
  args: {
    availableModifiers: [],
    selectedModifiers: [],
  },
  name: 'Empty state',
};

export const ManyModifiers: Story = {
  args: {
    availableModifiers: [
      ...SAMPLE_MODIFIERS,
      { termId: 'HP:0025153', label: 'Recurrent' },
      { termId: 'HP:0031797', label: 'Cyclic' },
      { termId: 'HP:0025302', label: 'Fluctuating' },
      { termId: 'HP:0011009', label: 'Sudden onset' },
    ],
    selectedModifiers: [SAMPLE_MODIFIERS[0]],
  },
  name: 'Long list (scroll check)',
};